[cluster]
    # 集群网关配置
    [cluster.gate]
        # 实例ID，网关集群中唯一。不填写默认自动生成唯一的实例ID
        id = ""
        # 实例名称
        name = "gate"
[transport]
    # GRPC相关配置
    [transport.grpc]
        # GRPC服务器相关配置
        [transport.grpc.server]
            # 服务器监听地址
            addr = ":8661"
            # 秘钥文件
            keyFile = ""
            # 证书文件
            certFile = ""
        # GRPC客户端相关配置
        [transport.grpc.client]
            # 证书文件
            certFile = ""
            # 证书域名
            serverName = ""
[packet]
    # 字节序，little | big
    endian = "big"
    # 序列号字节长度（字节）
    seqBytesLen = 2
    # 路由字节长度（字节）
    routeBytesLen = 2
[log]
    # 日志输出文件
    file = "./log/due.log"
    # 日志输出级别，可选：debug | info | warn | error | fatal | panic
    level = "info"
    # 日志输出格式，可选：text | json
    format = "text"
    # 是否输出到终端
    stdout = true
    # 时间格式，标准库时间格式
    timeFormat = "2006/01/02 15:04:05.000000"
    # 堆栈的最低输出级别，可选：debug | info | warn | error | fatal | panic
    stackLevel = "error"
    # 文件最大留存时间，d:天、h:时、m:分、s:秒
    fileMaxAge = "7d"
    # 文件最大尺寸限制，单位（MB）
    fileMaxSize = 100
    # 文件切割方式
    fileCutRule = "day"
    # 是否启用调用文件全路径
    callerFullPath = true
    # 是否启用分级存储
    classifiedStorage = true
    # zap日志组件。以下配置项如果不存在，则会使用log域中的默认配置项；如果均未配置，则会使用系统默认配置
[locate]
    [locate.redis]
        # 客户端连接地址
        addrs = ["127.0.0.1:6379"]
        # 数据库号
        db = 0
        # 用户名
        username = ""
        # 密码
        password = ""
        # 最大重试次数
        maxRetries = 3
        # key前缀
        prefix = "due"
[network]
    [network.ws]
        [network.ws.server]
            # 服务器监听地址
            addr = ":3553"
            # 客户端连接路径
            path = "/"
            # 最大消息长度（字节），默认1kb
            maxMsgLen = 1024
            # 服务器最大连接数
            maxConnNum = 5000
            # 秘钥文件
            keyFile = ""
            # 证书文件
            certFile = ""
            # 跨域检测，空数组时不允许任何连接升级成websocket，未设置此参数时允许所有的链接升级成websocket
            origins = ["*"]
            # 是否启用心跳检测，默认不启用
            heartbeatCheck = true
            # 心跳检测间隔时间（秒），默认为10秒
            heartbeatCheckInterval = 10
            # 握手超时时间（秒），默认10秒
            handshakeTimeout = 10
        [network.ws.client]
            # 拨号地址
            url = "ws://127.0.0.1:3553"
            # 最大消息长度（字节），默认1kb
            maxMsgLen = 1024
            # 握手超时时间（秒）
            handshakeTimeout = 10
            # 是否启用心跳，默认不启用
            heartbeat = false
            # 心跳间隔时间（秒），默认为10秒
            heartbeatInterval = 10
[registry]
    [registry.etcd]
        # 客户端连接地址
        addrs = ["127.0.0.1:2379"]
        # 客户端拨号超时时间（秒）
        dialTimeout = 5
        # 命名空间
        namespace = "services"
        # 超时时间（秒）
        timeout = 3
        # 心跳重试次数
        retryTimes = 3
        # 心跳重试间隔（秒）
        retryInterval = 10